### ISSUE TITLE
Tab issue with Guardian Spirit of Purification

### ISSUE THREAD

**Issue by xthekrakenx** [xeropresence/AOPP#1]
First - Awesome Patch - TY for the contribution!!! :) However while testing it in a brink mission, when I tab to try and find mobs - it correctly will not tab the (Guardian Spirit of Purification) for the first tab attempt,.. however if I hit tab again (at the start of the mission before mobs are available) - it will freeze the client. I have been able to repeat these steps. Checking the log files do not reveal anything that I can tell. Please halp! :)

**Comment by xeropresence** [comment]
Resolved with 283eb57fb079ef9d54171184a5808e38981c1395

**Comment by xthekrakenx** [comment]
TY for the super quick turn around. Issue has worsened - crashes on first tabbing now.

**Comment by xeropresence** [comment]
Whats your party makeup?

What faction are you, what faction is the person who pulled the mission?

**Comment by xeropresence** [comment]
[mswsock.zip](https://github.com/xeropresence/AOPP/files/4283869/mswsock.zip)

Please try this attached version and let me know if it resolves your issue.

**Comment by xthekrakenx** [comment]
Party makeup has varied both times, but faction has remained the same (Omni) including mission puller. The latest mswsock above appears to work - just tested 1st wave spirit spawn (which previously crashed me), So far so good - I will try an entire mission and confirm later today. TYVM for all of the hard work!! :)
