### ISSUE TITLE
GMI issue - Tries to load Full Automatic Targeting 

### ISSUE THREAD

**Issue by Lopnk** [xeropresence/AOPP#5]
When using the GMI , very often when searching for something and you want to look at orders. it will attempt to load but gets hung up and is show "full automatic targeting" in the description. you can see the orders but cannot interact with them

**Comment by xeropresence** [comment]
Can you record a video of it happening? Does it still happen after disabling the GMI patch via /aopp CommaGMIPatch

**Comment by Lopnk** [comment]
Here is a video
https://youtu.be/d0vJUF9RTAg
It always happens if only 1 item is on the list or near the bottom of the list

**Comment by xeropresence** [comment]
I can confirm and reproduce the issue. For now I would recommend disabling it via "/aopp CommaGMIPatch enabled false" and restarting the game

**Comment by xeropresence** [comment]
[update.zip](https://github.com/xeropresence/AOPP/files/15441873/update.zip)
Can you try replacing it with this version? You might need a newer version of the vcredist. I don't have an active sub but i was able to do some testing on a froob account.

**Comment by Lopnk** [comment]
I can test that update, I am not running any anti virus etc as an AOsharp user that stuff is all off

**Comment by Lopnk** [comment]
Same test as in my video. things seem to be loading fine at this time. I will check back in if the issue resurfaces

**Comment by xeropresence** [comment]
Can you test buy/sell orders with a comma, and withdrawing money with a comma?

**Comment by Lopnk** [comment]
> Can you test buy/sell orders with a comma, and withdrawing money with a comma?

Withdraw money with comma works fine
Creating sell orders does not
creating buy orders does not

**Comment by xeropresence** [comment]
[update.zip](https://github.com/user-attachments/files/15506215/update.zip)

Please try this version. Can you also test withdrawing money.

**Comment by xeropresence** [comment]
Gonna close this with https://github.com/xeropresence/AOPP/commit/5e3104fdcce79f7d23937c25ef961883a693c95c If there are areas where the comma doesn't work please let me know.
