### ISSUE TITLE
Virusalarm

### ISSUE THREAD

**Issue by Enfodoug** [xeropresence/AOPP#6]
https://www.virustotal.com/gui/file-analysis/ZjQ4YWM5YWRmM2Q1Y2FkNDE3ZjlmMjYzMzJhMzBiYjU6MTcxNzk5Nzk4OQ==

Also: Windows 10 defender blocks the file when AO is loading it... 

Trojan:Win32/Ulthar.A!m

**Comment by xeropresence** [comment]
False positives, always can compile your self with ease if unsure. 

I'll submit a false positive report to the windows defender team, this was an issue with one of the previous builds many years ago.
